### ISSUE TITLE
Binary compatible with Rust flatc format?

### ISSUE THREAD

**Issue by elefthei** [dcastro/haskell-flatbuffers#9]
Hey, thanks for maintaining this, very cool work! I've been trying to pass flatbuffer serialized files from a Haskell program to a Rust program and failing. Just want to make sure this is binary compatible with `flatc` generated parsers, specifically the one for Rust.

I am using the same fbs file for the writing (Haskell) and reading (Rust) but I get gibberish.

**Comment by dcastro** [comment]
Hi, thank you for the kind words!

Yes, we have a fairly large test suite that checks that flatbuffers produced by this library can be parsed by `flatc` and vice-versa.
See the [`RoundTripThroughFlatcSpec`](https://github.com/dcastro/haskell-flatbuffers/blob/master/test/FlatBuffers/Integration/RoundTripThroughFlatcSpec.hs#L35-L54) module.

Do you have a small reproducible schema that fails to roundtrip?

I didn't check for compatibiity with any specific implementation (like rust's), only with flatc. At some point I did have some roundtrip tests for the java/scala lib, but those were eventually replaced with `flatc`.

**Comment by elefthei** [comment]
I tried the code you linked and you're absolutely correct, it's the Rust parser who is wrong. Thanks and closing!
